apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: { { .Values.mongodb.namespace } }
type: Opaque
stringData:
  username: { { .Values.mongodb.username } }
  password: { { .Values.mongodb.password } }
