apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: { { .Chart.Name } }
type: Opaque
stringData:
  mongodb-uri: 'mongodb://my-user:my-password@mongodb.{{ .Values.name }}.svc.cluster.local:27017/my-database'
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: { { .Chart.Name } }
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: { { .Chart.Name } }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.6
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
