name: Build and deploy

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run compile

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/sjannsen/store:latest
          docker push ghcr.io/sjannsen/store:latest
