name: Build and deploy

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run compile

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to GitLab Container Registry
        env:
          CONTAINER_USER: ${{ secrets.GIT_LAB_CI_CONTAINER_USER }}
          CONTAINER_PASSWORD: ${{ secrets.GIT_LAB_CI_CONTAINER_PASSWORD }}
        run: |
          AUTH_STRING=$(echo -n "${CONTAINER_USER}:${CONTAINER_PASSWORD}" | base64)
          echo "${CONTAINER_PASSWORD}" | docker login registry.gitlab.com -u "${CONTAINER_USER}" --password-stdin

      - name: Build and Push Docker Image to GitLab Container Registry
        env:
          MSD_CONTAINER_AUTH_TOKEN: ${{ secrets.GIT_LAB_CI_MSD_CONTAINER_AUTH_TOKEN }}
          CONTAINER_USER: ${{ secrets.GIT_LAB_CI_CONTAINER_USER }}
        run: |
          docker build -t registry.gitlab.com/the-microservice-dungeon/devops-team/msd-image-registry/player-big-daddy-6969:latest .
          docker push registry.gitlab.com/the-microservice-dungeon/devops-team/msd-image-registry/player-big-daddy-6969:latest

      - name: Helm Setup
        uses: Azure/setup-helm@v3

      - name: Package Helm Chart
        run: | 
          helm dependency update ./helm-chart
          helm package ./helm-chart

      - name: Login to Helm Registry
        env:
          HELM_REGISTRY_USER: ${{ secrets.GIT_LAB_CI_CONTAINER_USER }}
          HELM_REGISTRY_PASSWORD: ${{ secrets.GIT_LAB_CI_CONTAINER_PASSWORD }}
        run: |
          helm registry login -u $HELM_REGISTRY_USER -p $HELM_REGISTRY_PASSWORD https://gitlab.com/api/v4/projects/42239222/packages/helm/stable
          helm plugin install --version=v0.10.4 https://github.com/chartmuseum/helm-push.git
          helm repo add --username $HELM_REGISTRY_USER --password $HELM_REGISTRY_PASSWORD player-big-daddy-6969 https://gitlab.com/api/v4/projects/42239222/packages/helm/stable
          helm cm-push player-big-daddy-6969*.tgz player-big-daddy-6969
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and Push Docker Image to GitHub Container Registry
        run: |
          docker build . --tag ghcr.io/sjannsen/player-big-daddy-6969:latest
          docker push ghcr.io/sjannsen/player-big-daddy-6969
